FROM node:18-alpine

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev

WORKDIR /nexus/
COPY package.json package-lock.json ./
RUN npm config set fetch-retry-maxtimeout 600000 -g

WORKDIR /nexus/app

COPY . .
ENV PATH /nexus/node_modules/.bin:$PATH
RUN chown -R node:node /nexus/app
USER node

RUN npm install

EXPOSE 1337

CMD ["npm", "run", "dev"]